try {
  statements;
}
catch(Exception e){
  statements;
}
